# Generated by Django 5.1.1 on 2024-09-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0002_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redactor",
            name="years_of_experience",
        ),
        migrations.AddField(
            model_name="redactor",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
