# Generated by Django 5.1.1 on 2024-09-25 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0004_remove_redactor_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="redactors",
            field=models.ManyToManyField(
                related_name="newspapers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
